### Type definitions saved at 2020-01-14T20:49:13.128Z ###

type MarkdownRemark implements Node @childOf(mimeTypes: ["text/markdown", "text/x-markdown"], types: [], many: false) @derivedTypes @dontInfer {
  frontmatter: MarkdownRemarkFrontmatter
  excerpt: String
  rawMarkdownBody: String
  fileAbsolutePath: String
  fields: MarkdownRemarkFields
}

type MarkdownRemarkFrontmatter @derivedTypes {
  timetable: File @fileByRelativePath
  price_early: Float
  price: Float
  title: String
  templateKey: String
  description: String
  image: File @fileByRelativePath
  info1: MarkdownRemark @link(by: "frontmatter.title")
  info2: MarkdownRemark @link(by: "frontmatter.title")
  images: [MarkdownRemarkFrontmatterImages]
  location: String
  artist: MarkdownRemark @link(by: "frontmatter.title")
  event: MarkdownRemark @link(by: "frontmatter.title")
  time: String
  announced: Boolean
  lineup: Boolean
  order: Int
  name: String
  eventbrite: String
  url: String
  links: [MarkdownRemarkFrontmatterLinks]
  status: String
  date: Date @dateformat
  early_bird: Date @dateformat
  active: Boolean
  category: String
  events: [MarkdownRemark] @link(by: "frontmatter.title")
}

type MarkdownRemarkFrontmatterLinks {
  name: String
  url: String
}

type MarkdownRemarkFrontmatterImages {
  alt: String
  image: File @fileByRelativePath
}

type MarkdownRemarkFields {
  slug: String
}